/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'C-PN18' at '6/27/19 12:06 PM' with Gradle 2.14.1
 *
 * @author C-PN18, @date 6/27/19 12:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
